# Site settings
title: Anto Dominic
meta_title: Anto Dominic | Portfolio & Blog
email: antodoms@pepalo.com
url: https://www.antodominic.com
description: "FullStack Developer, Entrepreneur, Tech Geek ,Social Media Enthusiast and IEEE volunteer. Interested in Embedded System, Robotics and Programming."
keywords: "Full Stack Developer, Ruby on Rails Developer, Salesforce Developer, Devops, AWS, Heroku, Blockchain"
skills: "Ruby on Rails Developer - DevOps Specialist - AWS Solution Architect"
meta_author: Anto Dominic

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: www.antodominic.com
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://www.twitter.com/antodoms
  - title: facebook
    url: https://www.facebook.com/antodoms
  - title: stack-overflow
    url: https://stackexchange.com/users/5385206/anto-dominic?tab=accounts
  - title: linkedin
    url: https://in.linkedin.com/pub/anto-dominic/26/742/118/
  - title: github
    url: https://github.com/antodoms

# Postal address (add as many lines as necessary)
address:
  - line: Parcel Collect 10080 17409
  - line: Shop 5d, 340 Craigieburn Road
  - line: Craigieburn VIC 3064

# Credits content
credits: 'This website is powered by Jekyll and hosted in Github pages.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

collections:
  projects: